import type { Metadata } from "next";

import "./globals.css";
import "./supabase/client";

export const metadata: Metadata = {
  title: "next-with-supabase",
  description: "Generated by create next app",
};

export default function HTMLLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={"antialiased"}>{children}</body>
    </html>
  );
}
